FROM hk/aws-lambda-cpp:0.2.7-2

ARG CC=/usr/local/bin/clang
ARG CXX=/usr/local/bin/clang++

RUN yum -y update && \
    yum -y install rsync openssl-static curl-devel openssl-devel && \
    curl -sL https://rpm.nodesource.com/setup_16.x | bash - && \
    yum -y install nodejs && \
    node -v && \
    npm -v && \
    npm install -g typescript && \
    npm install -g aws-cdk && \
    mkdir -p /tmp/aws-sdk-cpp && \
    cd /tmp/ && \    
    git clone --recurse-submodules https://github.com/hklabbers/aws-sdk-cpp && \
    mkdir aws-sdk-cpp/build && \
    cd aws-sdk-cpp/build && \
    cmake ../ -DCMAKE_BUILD_TYPE=Debug -DBUILD_SHARED_LIBS=OFF -DCPP_STANDARD=17 -DENABLE_TESTING=OFF && \
    make -j4 && \
    make install && \
    cd /tmp && \
    rm -rf aws-sdk-cpp
