FROM hk/aws-sdk-cpp:1.9.268-1

RUN yum install -y libpng libpng-devel libjpeg libjpeg-devel && \
    git clone https://github.com/opencv/opencv && \
    git -C opencv checkout 4.5.5 && \
    cd opencv && \
    mkdir build && \
    cd build && \
    cmake -DBUILD_SHARED_LIBS=off -DWITH_JPEG=ON -DWITH_PNG=ON -DCMAKE_BUILD_TYPE=Release .. && \
    make && \
    make install && \
    cd ../.. && \
    rm -rf opencv
